title: JohnnyBlocks's Steam Deck Guide
author:
  name: JohnnyBlocks
  email: Johnny.Blocks@NorthCoastBikeLife.org
description: > # this means to ignore newlines until "show_excerpts:"
  JohnnyBlocks's Collection of Resources and How To Do's to let you LEVEL-UP your Steam Deck.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d %H:%M"

  # generate social links in footer
  social_links:
    #- { platform: devto,          user_url: "https://dev.to/jekyll" }
    #- { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    #- { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    #- { platform: flickr,         user_url: "https://www.flickr.com/photos/JohnnyBlocks" }
    - { platform: github,         user_url: "https://github.com/JohnnyBlocks" }
    #- { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    - { platform: instagram,      user_url: "https://www.instagram.com/JohnnyBlocks" }
    #- { platform: keybase,        user_url: "https://keybase.io/JohnnyBlocks" }
    #- { platform: linkedin,       user_url: "https://www.linkedin.com/in/JohnnyBlocks" }
    #- { platform: microdotblog,   user_url: "https://micro.blog/JohnnyBlocks" }
    #- { platform: pinterest,      user_url: "https://www.pinterest.com/JohnnyBlocks" }
    #- { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/JohnnyBlocks" }
    - { platform: telegram,       user_url: "https://t.me/JohnnyBlocks" }
    #- { platform: twitter,        user_url: "https://twitter.com/JohnnyBlocks" }
    - { platform: youtube,        user_url: "https://www.youtube.com/@JohnnyBlocks" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag